(raise RuntimeError.new("(= 1) is not true") unless true)
(raise RuntimeError.new("(= 1 1) is not true") unless (1 == 1))
(raise RuntimeError.new("(= 1 1 1) is not true") unless ((1 == 1) && (1 == 1)))
(raise RuntimeError.new("(= 1 1 1 1) is not true") unless ((1 == 1) && (1 == 1) && (1 == 1)))
(raise RuntimeError.new("(not (= 1 2)) is not true") unless !(1 == 2))
(raise RuntimeError.new("(not (= 1 2 1)) is not true") unless !((1 == 2) && (2 == 1)))
(raise RuntimeError.new("(not (= 1 1 2)) is not true") unless !((1 == 1) && (1 == 2)))
(raise RuntimeError.new("(not (= 1 1 2 1)) is not true") unless !((1 == 1) && (1 == 2) && (2 == 1)))
(raise RuntimeError.new("(not (= 1 1 1 2)) is not true") unless !((1 == 1) && (1 == 1) && (1 == 2)))